# -*- coding: utf-8 -*-
"""Regresi Linear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17SVaRr17xRtCmtsJEX6EvDp-WTXE51iK
"""

import numpy as np # modul numpy untuk memudahkan pengolahan data
from sklearn.linear_model import LinearRegression # modul untuk memproses data

# Database
# x = Data, y = Target
x = [[2],[4],[8],[10],[12],[14],[16],[18],[20],[22]]
y = [4, 8, 16, 20, 24, 28, 32, 36, 40, 44] # hasil kali 2 dari nilai x

regr = LinearRegression().fit(x,y) # meregresi dan menampilkan grafik
regr.score(x,y) # menghasilkan nilai

# Data uji
predict = np.array([[60]]) # nilai yang diprediksi

# Menampilkan data prediksi
print ("Citra Dwi Lestari 1207030009") # menampilkan nama dan nim
print ("Prediksi") # menampilkan kata prediksi
print ("Input = ", predict) # menampilkan kata input dari nilai prediksi
print ("Output = ", regr.predict(predict)) # menampilkan kata output dari nilai regresi prediksi